style_edition     = "2024"
unstable_features = true

format_code_in_doc_comments = true
format_macro_bodies         = true
format_macro_matchers       = true
format_strings              = true
group_imports               = "StdExternalCrate"
imports_granularity         = "Crate"
wrap_comments               = true
